export const ActionTypes = {
  SET_FILES: "SET_FILES",
  USER_SET_FILES: "USER_SET_FILES",
  USER_DELETE_FILE: "USER_DELETE_FILE",
  USER_EDIT_FILE: "USER_EDIT_FILE",
  USER_SET_RAW_DATA: "USER_SET_RAW_DATA",
};
